# Generated by Django 5.1.5 on 2025-02-11 17:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0002_messagebody'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageBody',
            new_name='Message',
        ),
    ]
