# Generated by Django 5.1.5 on 2025-02-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0006_alter_message_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Created',
            new_name='messageCreated',
        ),
    ]
