# Generated by Django 5.1.5 on 2025-02-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0008_alter_message_messagecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='BlogIm',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
