# Generated by Django 5.1.5 on 2025-02-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0011_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Image',
            field=models.ImageField(blank=True, default="{% static 'Media/Userprofile' %}", upload_to='images/'),
        ),
    ]
