# Generated by Django 5.1.6 on 2025-02-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0012_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(default='Messagebody'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Image',
            field=models.ImageField(blank=True, default='/Userprofile/user.png', upload_to='images/'),
        ),
    ]
