# Generated by Django 5.1.6 on 2025-02-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0013_alter_message_body_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='messga_body',
        ),
    ]
