# Generated by Django 5.1.6 on 2025-02-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0014_rename_body_message_messga_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='messga_body',
        ),
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.TextField(default='Messagebody', null=True),
        ),
    ]
