# Generated by Django 5.1.6 on 2025-02-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0015_remove_message_messga_body_message_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Image',
            field=models.ImageField(blank=True, default='/Userprofile/user.png', upload_to='Userprofile/'),
        ),
    ]
