# Generated by Django 5.1.5 on 2025-03-02 15:17

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0017_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='title',
        ),
        migrations.CreateModel(
            name='BlogmodelTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='simpleblog.blogmodel')),
            ],
            options={
                'verbose_name': 'blogmodel Translation',
                'db_table': 'simpleblog_blogmodel_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
