# Generated by Django 5.1.5 on 2025-03-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0018_remove_blogmodel_description_remove_blogmodel_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
        migrations.DeleteModel(
            name='BlogmodelTranslation',
        ),
    ]
